# Generated by Django 5.0.1 on 2024-01-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fulname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
