# Generated by Django 5.0.1 on 2024-01-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_fulname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fulname',
        ),
    ]
