# Generated by Django 5.0.1 on 2024-01-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_fulname'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product_favorites',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
